namespace :import do

  desc 'Import trade codes'
  task :trade_codes => [:environment] do
    puts "#{TradeCode.delete_all} trade codes deleted"
    terms = [
      {:code => 'BAL', :name => 'baleen'},
      {:code => 'BAR', :name => 'bark'},
      {:code => 'BEL', :name => 'belts'},
      {:code => 'BOD', :name => 'bodies'},
      {:code => 'BOC', :name => 'bone carvings'},
      {:code => 'BOP', :name => 'bone pieces'},
      {:code => 'BPR', :name => 'bone products'},
      {:code => 'BON', :name => 'bones'},
      {:code => 'CAL', :name => 'calipee'},
      {:code => 'CAP', :name => 'carapaces'},
      {:code => 'CAR', :name => 'carvings'},
      {:code => 'CAV', :name => 'caviar'},
      {:code => 'CST', :name => 'chess sets'},
      {:code => 'CHP', :name => 'chips'},
      {:code => 'CLA', :name => 'claws'},
      {:code => 'CLO', :name => 'cloth'},
      {:code => 'COS', :name => 'coral sand'},
      {:code => 'CUL', :name => 'cultures'},
      {:code => 'DER', :name => 'derivatives'},
      {:code => 'DPL', :name => 'dried plants'},
      {:code => 'EAR', :name => 'ears'},
      {:code => 'EGG', :name => 'eggs'},
      {:code => 'EGL', :name => 'eggs (live)'},
      {:code => 'EXT', :name => 'extract'},
      {:code => 'FEA', :name => 'feathers'},
      {:code => 'FOO', :name => 'feet'},
      {:code => 'FIB', :name => 'fibres'},
      {:code => 'FIG', :name => 'fingerlings'},
      {:code => 'FIN', :name => 'fins'},
      {:code => 'FPT', :name => 'flower pots'},
      {:code => 'FLO', :name => 'flowers'},
      {:code => 'FRU', :name => 'fruit'},
      {:code => 'GAL', :name => 'gall'},
      {:code => 'GAB', :name => 'gall bladder(s)'},
      {:code => 'GAR', :name => 'garments'},
      {:code => 'GEN', :name => 'genitalia'},
      {:code => 'GRS', :name => 'graft rootstocks'},
      {:code => 'HAI', :name => 'hair'},
      {:code => 'HAP', :name => 'hair products'},
      {:code => 'HAN', :name => 'handbags'},
      {:code => 'HEA', :name => 'heads'},
      {:code => 'HOC', :name => 'horn carvings'},
      {:code => 'HOP', :name => 'horn pieces'},
      {:code => 'HPR', :name => 'horn products'},
      {:code => 'HOS', :name => 'horn scraps'},
      {:code => 'HOR', :name => 'horns'},
      {:code => 'FRN', :name => 'items of furniture'},
      {:code => 'IVC', :name => 'ivory carvings'},
      {:code => 'IVP', :name => 'ivory pieces'},
      {:code => 'IVS', :name => 'ivory scraps'},
      {:code => 'LEA', :name => 'leather'},
      {:code => 'SKO', :name => 'leather items'},
      {:code => 'LPL', :name => 'leather products (l)'},
      {:code => 'LPS', :name => 'leather products (s)'},
      {:code => 'LVS', :name => 'leaves'},
      {:code => 'LEG', :name => 'legs'},
      {:code => 'LIV', :name => 'live'},
      {:code => 'LOG', :name => 'logs'},
      {:code => 'MEA', :name => 'meat'},
      {:code => 'MED', :name => 'medicine'},
      {:code => 'MUS', :name => 'musk'},
      {:code => 'OIL', :name => 'oil'},
      {:code => 'OTH', :name => 'other'},
      {:code => 'SHO', :name => 'pairs of shoes'},
      {:code => 'PEA', :name => 'pearls'},
      {:code => 'PKY', :name => 'piano keys'},
      {:code => 'PIE', :name => 'pieces'},
      {:code => 'PLA', :name => 'plates'},
      {:code => 'PLY', :name => 'plywood'},
      {:code => 'POW', :name => 'powder'},
      {:code => 'QUI', :name => 'quills'},
      {:code => 'COR', :name => 'raw corals'},
      {:code => 'ROO', :name => 'roots'},
      {:code => 'SAW', :name => 'sawn wood'},
      {:code => 'SCA', :name => 'scales'},
      {:code => 'SCR', :name => 'scraps'},
      {:code => 'SEE', :name => 'seeds'},
      {:code => 'SHE', :name => 'shells'},
      {:code => 'SKD', :name => 'sides'},
      {:code => 'SID', :name => 'sides'},
      {:code => 'SKE', :name => 'skeletons'},
      {:code => 'SKP', :name => 'skin pieces'},
      {:code => 'SKS', :name => 'skin scraps'},
      {:code => 'SKI', :name => 'skins'},
      {:code => 'SKU', :name => 'skulls'},
      {:code => 'SOU', :name => 'soup'},
      {:code => 'SPE', :name => 'specimens'},
      {:code => 'FRA', :name => 'spectacle frames'},
      {:code => 'STE', :name => 'stems'},
      {:code => 'SWI', :name => 'swim bladders'},
      {:code => 'TAI', :name => 'tails'},
      {:code => 'TEE', :name => 'teeth'},
      {:code => 'TIM', :name => 'timber'},
      {:code => 'TIC', :name => 'timber carvings'},
      {:code => 'TIP', :name => 'timber pieces'},
      {:code => 'TIS', :name => 'tissue cultures'},
      {:code => 'TRO', :name => 'trophies'},
      {:code => 'TUS', :name => 'tusks'},
      {:code => 'VEN', :name => 'veneer'},
      {:code => 'VNM', :name => 'venom'},
      {:code => 'WAL', :name => 'wallets'},
      {:code => 'WAT', :name => 'watchstraps'},
      {:code => 'WAX', :name => 'wax'},
      {:code => 'WOO', :name => 'wood products'}
    ]
    terms.each{ |t| Term.create(t) }

    sources = [
      {:code => 'A', :name => 'Artificially propagated plants'},
      {:code => 'C', :name => 'Captive-bred animals'},
      {:code => 'D', :name => 'Captive-bred/artificially propagated (Appendix I)'},
      {:code => 'F', :name => 'Born in captivity (F1 and subsequent)'},
      {:code => 'I', :name => 'Confiscations/seizures'},
      {:code => 'O', :name => 'Pre-Convention'},
      {:code => 'R', :name => 'Ranched'},
      {:code => 'W', :name => 'Wild'}
    ]
    sources.each{ |t| Source.create(t) }

    purposes = [
      {:code => 'B', :name => 'Breeding in captivity or artificially propagation'},
      {:code => 'E', :name => 'Educational'},
      {:code => 'G', :name => 'Botanical garden'},
      {:code => 'H', :name => 'Hunting trophy'},
      {:code => 'L', :name => 'Law enforcement/judicial/forensic'},
      {:code => 'M', :name => 'Medical (including biomedical research)'},
      {:code => 'N', :name => 'Reintroduction or introduction into the wild'},
      {:code => 'P', :name => 'Personal'},
      {:code => 'Q', :name => 'Circus and travelling exhibitions'},
      {:code => 'S', :name => 'Scientific'},
      {:code => 'T', :name => 'Commercial'},
      {:code => 'Z', :name => 'Zoo'}
    ]
    purposes.each{ |t| Purpose.create(t) }

    units = [
      {:code => 'BAG', :name => 'Bags'},
      {:code => 'BAK', :name => 'Back skins'},
      {:code => 'BOT', :name => 'Bottles'},
      {:code => 'BOX', :name => 'Boxes'},
      {:code => 'BSK', :name => 'Belly skins'},
      {:code => 'CAN', :name => 'Cans'},
      {:code => 'CAS', :name => 'Cases'},
      {:code => 'CCM', :name => 'Cubic centimetres'},
      {:code => 'CRT', :name => 'Cartons'},
      {:code => 'CTM', :name => 'Centimetres'},
      {:code => 'CUF', :name => 'Cubic feet'},
      {:code => 'CUM', :name => 'Cubic metres'},
      {:code => 'FEE', :name => 'Feet'},
      {:code => 'FLA', :name => 'Flasks'},
      {:code => 'GRM', :name => 'Grams'},
      {:code => 'HRN', :name => 'Hornback skins'},
      {:code => 'INC', :name => 'Inches'},
      {:code => 'ITE', :name => 'Items'},
      {:code => 'KIL', :name => 'Kilograms'},
      {:code => 'LTR', :name => 'Litres'},
      {:code => 'MGM', :name => 'Milligrams'},
      {:code => 'MLT', :name => 'Millilitres'},
      {:code => 'MTR', :name => 'Metres'},
      {:code => 'MYG', :name => 'Micrograms'},
      {:code => 'OUN', :name => 'Ounces'},
      {:code => 'PAI', :name => 'Pairs'},
      {:code => 'PCS', :name => 'Pieces'},
      {:code => 'PND', :name => 'Pounds'},
      {:code => 'SET', :name => 'Sets'},
      {:code => 'SHP', :name => 'Shipments'},
      {:code => 'SID', :name => 'Sides'},
      {:code => 'SKI', :name => 'Skins'},
      {:code => 'SQC', :name => 'Square centimetres'},
      {:code => 'SQD', :name => 'Square decimetres'},
      {:code => 'SQF', :name => 'Square feet'},
      {:code => 'SQM', :name => 'Square metres'},
      {:code => 'TON', :name => 'Metric tons'}
    ]
    units.each{ |t| Unit.create(t) }

    puts "#{TradeCode.count} trade codes created"
  end

end
