# inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 3.0.6
  TargetRailsVersion: 6.0
  Exclude:
    - 'lib/tasks/bbgem.rake'
    - 'db/schema.rb'
    - 'old_cap/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: outdent, indent
Layout/AccessModifierIndentation:
  EnforcedStyle: indent

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: normal, rails
Layout/IndentationConsistency:
  EnforcedStyle: normal
  Exclude:
    - 'db/migrate/*'

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: symmetrical, new_line, same_line
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: symmetrical

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: symmetrical, new_line, same_line
Layout/MultilineHashBraceLayout:
  EnforcedStyle: symmetrical

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: always, conditionals
Style/AndOr:
  Exclude:
    - 'db/migrate/*'

# Offense count: 551
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: leading, trailing
Layout/DotPosition:
  EnforcedStyle: trailing

# Configuration parameters: AllowForAlignment, ForceEqualSignAlignment.
Layout/ExtraSpacing:
  AllowForAlignment: true
  Exclude:
    - 'db/migrate/*'

# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: consistent, special_for_inner_method_call, special_for_inner_method_call_in_parentheses
Layout/FirstParameterIndentation:
  Enabled: true

# Configuration parameters: Width.
Layout/IndentationWidth:
  Exclude:
    - 'db/migrate/*'

# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
# SupportedStyles: space, no_space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

# Configuration parameters: AllowForAlignment.
Layout/SpaceAroundOperators:
  AllowForAlignment: true

# Configuration parameters: AllowIfMethodIsEmpty.
Style/SingleLineMethods:
  AllowIfMethodIsEmpty: true

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/BlockAlignment:
  EnforcedStyleAlignWith: either

Layout/CaseIndentation:
  EnforcedStyle: end

Metrics/MethodLength:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: always_ignore

Rails/NotNullColumn:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
