# docker-compose.yml
version: '3.8'

networks:
  sapi:
    driver: bridge

services:
  db:
    container_name: sapi-db
    image: postgres:10
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    ports:
      - "${SAPI_DATABASE_PORT:-5432}:5432"
    networks:
      - sapi
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "sapi_development"

  rails:
    container_name: sapi-rails
    build:
      context: ./
      dockerfile: Dockerfile
    command: /bin/bash -l -c "rm -f ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - '.:/SAPI'
      - bundler_gems:/usr/local/bundle
    ports:
      - '${SAPI_PORT:-3000}:3000'
    networks:
      - sapi
    stdin_open: true
    tty: true
    environment:
      MAILER_ADDRESS: sapi-mailcatcher
      SAPI_DATABASE_HOST: sapi-db
      SAPI_DATABASE_PORT: "${SAPI_DATABASE_PORT:-5432}"
      SAPI_SIDEKIQ_REDIS_URL: redis://sapi-redis:6379/0
    depends_on:
      - redis
      - db
      - mailcatcher

  redis:
    container_name: sapi-redis
    image: redis:7.2.0
    ports:
      - "6379:6379"
    networks:
      - sapi
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data

  sidekiq:
    container_name: sapi-sidekiq
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - sapi
    depends_on:
      - db
      - redis
      - mailcatcher
    command: /bin/bash -l -c "bundle install && bundle exec sidekiq -C config/sidekiq.yml"
    volumes:
      - '.:/SAPI'
      - bundler_gems:/usr/local/bundle
    environment:
      MAILER_ADDRESS: sapi-mailcatcher
      SAPI_DATABASE_HOST: sapi-db
      SAPI_DATABASE_PORT: "${SAPI_DATABASE_PORT:-5432}"
      SAPI_SIDEKIQ_REDIS_URL: redis://sapi-redis:6379/0

  mailcatcher:
    container_name: sapi-mailcatcher
    image: sj26/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'
    networks:
      - sapi

volumes:
  pgdata:
  bundler_gems:
  redis_data:
