# Run this at 02:42 on Saturday mornings.
#
# We need to time this so it doesn't conflict with the daily backups, which
# take AccessShareLocks and currently run until 02:10.
rebuild_job_weekly:
  cron: "42 2 * * 6"
  class: "RebuildJob"
  queue: admin

# NB: we should manually disable the following job on production
rebuild_job_daily:
  cron: "42 2 * * 0-5"
  class: "RebuildJob"
  queue: admin

# This needs to happen late enough that the rebuild job has completed
downloads_cache_update_job:
  cron: "5 6 * * *"
  class: "DownloadsCacheUpdateJob"
  queue: admin

purge_unattached_job:
  cron: "0 18 * * *"
  class: "PurgeUnattachedJob"
  queue: admin

sunday_cleanup_job:
  cron: "45 4 * * 0"
  class: "SundayCleanupJob"
  queue: admin

elibrary_refresh_document_search_job:
  cron: "*/5 * * * *"
  class: "ElibraryRefreshDocumentSearchJob"
  queue: admin

refresh_sitemap_job:
  cron: "30 5 * * *"
  class: "RefreshSitemapJob"
  queue: admin

rst_processes_import_job:
  cron: "30 2 * * 0"
  class: "RstProcessesImportJob"
  queue: admin

refresh_api_downloads_job:
  cron: "30 9 * * 0"
  class: "RefreshApiDownloadsJob"
  queue: admin
