# Run this at 02:42 on Saturday mornings.
#
# We need to time this so it doesn't conflict with the daily backups, which
# take AccessShareLocks and currently run until 02:10.
rebuild_job_weekly:
  cron: "42 2 * * 6"
  class: "RebuildJob"
  queue: admin

# NB: we should manually disable the following job on production
rebuild_job_daily:
  cron: "42 2 * * 0-5"
  class: "RebuildJob"
  queue: admin

downloads_cache_update_job:
  cron: "5 4 * * *"
  class: "DownloadsCacheUpdateJob"
  queue: admin
sunday_cleanup_job:
  cron: "45 4 * * 0"
  class: "SundayCleanupJob"
  queue: admin
elibrary_refresh_document_search_job:
  cron: "*/5 * * * *"
  class: "ElibraryRefreshDocumentSearchJob"
  queue: admin
refresh_sitemap_job:
  cron: "30 5 * * *"
  class: "RefreshSitemapJob"
  queue: admin
rst_processes_import_job:
  cron: "30 1 * * 0"
  class: "RstProcessesImportJob"
  queue: admin
