common: &defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailer:
    domain: <%= ENV["MAILER_DOMAIN"] %>
    address: <%= ENV["MAILER_ADDRESS"] %>
    username: <%= ENV["MAILER_USERNAME"] %>
    password: <%= ENV["MAILER_PASSWORD"] %>
    host: <%= ENV["MAILER_HOST"] %>
    from: <%= ENV["MAILER_USERNAME"] %>
  redis:
    namespace: 'SAPI'
    url: 'redis://127.0.0.1:6379/1'
  aws:
    bucket_name: <%= ENV["AWS_BUCKET_NAME"] %>
    access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  shipments_api_token: <%= ENV["SHIPMENTS_API_TOKEN"] %>
  cites_trade_full_download: <%= ENV["CITES_TRADE_FULL_DOWNLOAD_LINK"] %>
  rst_api_base_url: <%= ENV["RST_API_BASE_URL"] %>

development:
  <<: *defaults
  secret_key_base: 'fd7add8bc2abb8e206f5f43d432947b2407a67944a3f64555d19009501d3ff066de0caa717ba8ef6c31d7ee7fc8d26fae602da5b0ce0204eb3f21bfe1b33305a'
  capistrano_slack: ''
  iucn_redlist:
    token: ''
    url: ''
  cms:
    index:
    show:

production:
  <<: *defaults
  iucn_redlist:
    token: <%= ENV['IUCN_REDLIST_TOKEN'] %>
    url: <%= ENV['IUCN_REDLIST_URL'] %>
  cms:
    index: <%= ENV['CMS_INDEX'] %>
    show: <%= ENV['CMS_SHOW'] %>
  new_relic_api_key: <%= ENV['NEW_RELIC_API_KEY'] %>
  new_relic_app_id: <%= ENV['NEW_RELIC_APP_ID'] %>
  new_relic_license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
slack_exception_notification_token: <%= ENV['SLACK_EXCEPTION_NOTIFICATION_TOKEN'] %>
slack_exception_notification_webhook_url: <%= ENV['SLACK_EXCEPTION_NOTIFICATION_WEBHOOK_URL'] %>

staging:
  <<: *defaults

test:
  <<: *defaults
  secret_key_base: 'fd7add8bc2abb8e206f5f43d432947b2407a67944a3f64555d19009501d3ff066de0caa717ba8ef6c31d7ee7fc8d26fae602da5b0ce0204eb3f21bfe1b33305a'
