# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: false
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 2
production:
  :concurrency: 50
:queues:
  - [default, 5]
  - [trade, 5]
