# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: false
:pidfile: tmp/pids/sidekiq.pid # Comment out this line for docker local development, but don't commit to git. Server need this line.
staging:
  :concurrency: 2
production:
  :concurrency: 10
:queues:
  - [default, 7]
  - [admin, 4]
