class AddForeignKeyConstraintsToTrackingColumns < ActiveRecord::Migration
  def change
    add_foreign_key "common_names", "users", name: "common_names_created_by_id_fk", column: "created_by_id"
    add_foreign_key "common_names", "users", name: "common_names_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "trade_shipments", "users", name: "trade_shipments_created_by_id_fk", column: "created_by_id"
    add_foreign_key "trade_shipments", "users", name: "trade_shipments_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "listing_changes", "users", name: "listing_changes_created_by_id_fk", column: "created_by_id"
    add_foreign_key "listing_changes", "users", name: "listing_changes_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "trade_restrictions", "users", name: "trade_restrictions_created_by_id_fk", column: "created_by_id"
    add_foreign_key "trade_restrictions", "users", name: "trade_restrictions_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "eu_decisions", "users", name: "eu_decisions_created_by_id_fk", column: "created_by_id"
    add_foreign_key "eu_decisions", "users", name: "eu_decisions_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "events", "users", name: "events_created_by_id_fk", column: "created_by_id"
    add_foreign_key "events", "users", name: "events_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "distributions", "users", name: "distributions_created_by_id_fk", column: "created_by_id"
    add_foreign_key "distributions", "users", name: "distributions_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "trade_annual_report_uploads", "users", name: "trade_annual_report_uploads_created_by_id_fk", column: "created_by_id"
    add_foreign_key "trade_annual_report_uploads", "users", name: "trade_annual_report_uploads_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "taxon_concepts", "users", name: "taxon_concepts_created_by_id_fk", column: "created_by_id"
    add_foreign_key "taxon_concepts", "users", name: "taxon_concepts_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "taxon_relationships", "users", name: "taxon_relationships_created_by_id_fk", column: "created_by_id"
    add_foreign_key "taxon_relationships", "users", name: "taxon_relationships_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "references", "users", name: "references_created_by_id_fk", column: "created_by_id"
    add_foreign_key "references", "users", name: "references_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "taxon_concept_references", "users", name: "taxon_concept_references_created_by_id_fk", column: "created_by_id"
    add_foreign_key "taxon_concept_references", "users", name: "taxon_concept_references_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "distribution_references", "users", name: "distribution_references_created_by_id_fk", column: "created_by_id"
    add_foreign_key "distribution_references", "users", name: "distribution_references_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "taxon_commons", "users", name: "taxon_commons_created_by_id_fk", column: "created_by_id"
    add_foreign_key "taxon_commons", "users", name: "taxon_commons_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "listing_distributions", "users", name: "listing_distributions_created_by_id_fk", column: "created_by_id"
    add_foreign_key "listing_distributions", "users", name: "listing_distributions_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "annotations", "users", name: "annotations_created_by_id_fk", column: "created_by_id"
    add_foreign_key "annotations", "users", name: "annotations_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "trade_restriction_purposes", "users", name: "trade_restriction_purposes_created_by_id_fk", column: "created_by_id"
    add_foreign_key "trade_restriction_purposes", "users", name: "trade_restriction_purposes_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "trade_restriction_sources", "users", name: "trade_restriction_sources_created_by_id_fk", column: "created_by_id"
    add_foreign_key "trade_restriction_sources", "users", name: "trade_restriction_sources_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "trade_restriction_terms", "users", name: "trade_restriction_terms_created_by_id_fk", column: "created_by_id"
    add_foreign_key "trade_restriction_terms", "users", name: "trade_restriction_terms_updated_by_id_fk", column: "updated_by_id"
    add_foreign_key "taxon_instruments", "users", name: "taxon_instruments_created_by_id_fk", column: "created_by_id"
    add_foreign_key "taxon_instruments", "users", name: "taxon_instruments_updated_by_id_fk", column: "updated_by_id"
  end
end
