
class AddForeignKeyIndexes < ActiveRecord::Migration[7.1]
  def change
    safety_assured do
      indexes_to_add.each do |index_creation_args|
        add_index(*index_creation_args)
      end
    end
  end

private

  def indexes_to_add
    [
      [ :annotations, :created_by_id ],
      [ :annotations, :event_id ],
      [ :annotations, :original_id ],
      [ :annotations, :updated_by_id ],
      [ :change_types, :designation_id ],
      [ :cites_suspension_confirmations, :cites_suspension_id ],
      [ :cites_suspension_confirmations, :cites_suspension_notification_id ],
      [ :comments, :created_by_id ],
      [ :comments, :updated_by_id ],
      [ :common_names, :created_by_id ],
      [ :common_names, :language_id ],
      [ :common_names, :updated_by_id ],
      [ :designation_geo_entities, :designation_id ],
      [ :designation_geo_entities, :geo_entity_id ],
      [ :designations, :taxonomy_id ],
      [ :distribution_references, :created_by_id ],
      [ :distribution_references, :updated_by_id ],
      [ :distributions, :created_by_id ],
      [ :distributions, :updated_by_id ],
      [ :document_citation_geo_entities, :created_by_id ],
      [ :document_citation_geo_entities, :document_citation_id ],
      [ :document_citation_geo_entities, :geo_entity_id ],
      [ :document_citation_geo_entities, :updated_by_id ],
      [ :document_citation_taxon_concepts, :created_by_id ],
      [ :document_citation_taxon_concepts, :document_citation_id ],
      [ :document_citation_taxon_concepts, :taxon_concept_id ],
      [ :document_citation_taxon_concepts, :updated_by_id ],
      [ :document_citations, :created_by_id ],
      [ :document_citations, :updated_by_id ],
      [ :documents, :created_by_id ],
      [ :documents, :designation_id ],
      [ :documents, :language_id ],
      [ :documents, :original_id ],
      [ :documents, :primary_language_document_id ],
      [ :documents, :updated_by_id ],
      [ :eu_decision_confirmations, :eu_decision_id ],
      [ :eu_decision_confirmations, :event_id ],
      [ :eu_decisions, :created_by_id ],
      [ :eu_decisions, :end_event_id ],
      [ :eu_decisions, :eu_decision_type_id ],
      [ :eu_decisions, :geo_entity_id ],
      [ :eu_decisions, :source_id ],
      [ :eu_decisions, :srg_history_id ],
      [ :eu_decisions, :start_event_id ],
      [ :eu_decisions, :taxon_concept_id ],
      [ :eu_decisions, :term_id ],
      [ :eu_decisions, :updated_by_id ],
      [ :events, :created_by_id ],
      [ :events, :designation_id ],
      [ :events, :updated_by_id ],
      [ :geo_entities, :geo_entity_type_id ],
      [ :geo_relationships, :geo_entity_id ],
      [ :geo_relationships, :geo_relationship_type_id ],
      [ :geo_relationships, :other_geo_entity_id ],
      [ :instruments, :designation_id ],
      [ :listing_changes, :change_type_id ],
      [ :listing_changes, :created_by_id ],
      [ :listing_changes, :original_id ],
      [ :listing_changes, :species_listing_id ],
      [ :listing_changes, :updated_by_id ],
      [ :listing_distributions, :created_by_id ],
      [ :listing_distributions, :original_id ],
      [ :listing_distributions, :updated_by_id ],
      [ :nomenclature_change_inputs, :created_by_id ],
      [ :nomenclature_change_inputs, :nomenclature_change_id ],
      [ :nomenclature_change_inputs, :taxon_concept_id ],
      [ :nomenclature_change_inputs, :updated_by_id ],
      [ :nomenclature_change_output_reassignments, :created_by_id ],
      [ :nomenclature_change_output_reassignments, :nomenclature_change_output_id ],
      [ :nomenclature_change_output_reassignments, :updated_by_id ],
      [ :nomenclature_change_outputs, :created_by_id ],
      [ :nomenclature_change_outputs, :new_parent_id ],
      [ :nomenclature_change_outputs, :new_rank_id ],
      [ :nomenclature_change_outputs, :new_taxon_concept_id ],
      [ :nomenclature_change_outputs, :nomenclature_change_id ],
      [ :nomenclature_change_outputs, :taxon_concept_id ],
      [ :nomenclature_change_outputs, :updated_by_id ],
      [ :nomenclature_change_reassignment_targets, :created_by_id ],
      [ :nomenclature_change_reassignment_targets, :nomenclature_change_output_id ],
      [ :nomenclature_change_reassignment_targets, :nomenclature_change_reassignment_id ],
      [ :nomenclature_change_reassignment_targets, :updated_by_id ],
      [ :nomenclature_change_reassignments, :created_by_id ],
      [ :nomenclature_change_reassignments, :nomenclature_change_input_id ],
      [ :nomenclature_change_reassignments, :updated_by_id ],
      [ :nomenclature_changes, :created_by_id ],
      [ :nomenclature_changes, :event_id ],
      [ :nomenclature_changes, :updated_by_id ],
      [ :proposal_details, :document_id ],
      [ :references, :created_by_id ],
      [ :references, :updated_by_id ],
      [ :review_details, :document_id ],
      [ :species_listings, :designation_id ],
      [ :taxon_commons, :common_name_id ],
      [ :taxon_commons, :created_by_id ],
      [ :taxon_commons, :taxon_concept_id ],
      [ :taxon_commons, :updated_by_id ],
      [ :distributions, :geo_entity_id ],
      [ :taxon_concept_references, :created_by_id ],
      [ :taxon_concept_references, :reference_id ],
      [ :taxon_concept_references, :taxon_concept_id ],
      [ :taxon_concept_references, :updated_by_id ],
      [ :taxon_concepts, :created_by_id ],
      [ :taxon_concepts, :dependents_updated_by_id ],
      [ :taxon_concepts, :rank_id ],
      [ :taxon_concepts, :taxon_name_id ],
      [ :taxon_concepts, :updated_by_id ],
      [ :taxon_instruments, :created_by_id ],
      [ :taxon_instruments, :instrument_id ],
      [ :taxon_instruments, :updated_by_id ],
      [ :taxon_relationships, :created_by_id ],
      [ :taxon_relationships, :taxon_concept_id ],
      [ :taxon_relationships, :taxon_relationship_type_id ],
      [ :taxon_relationships, :updated_by_id ],
      [ :term_trade_codes_pairs, :term_id ],
      [ :term_trade_codes_pairs, :trade_code_id ],
      [ :trade_annual_report_uploads, :created_by ],
      [ :trade_annual_report_uploads, :created_by_id ],
      [ :trade_annual_report_uploads, :trading_country_id ],
      [ :trade_annual_report_uploads, :updated_by ],
      [ :trade_annual_report_uploads, :updated_by_id ],
      [ :trade_restriction_purposes, :created_by_id ],
      [ :trade_restriction_purposes, :purpose_id ],
      [ :trade_restriction_purposes, :trade_restriction_id ],
      [ :trade_restriction_purposes, :updated_by_id ],
      [ :trade_restriction_sources, :created_by_id ],
      [ :trade_restriction_sources, :source_id ],
      [ :trade_restriction_sources, :trade_restriction_id ],
      [ :trade_restriction_sources, :updated_by_id ],
      [ :trade_restriction_terms, :created_by_id ],
      [ :trade_restriction_terms, :term_id ],
      [ :trade_restriction_terms, :trade_restriction_id ],
      [ :trade_restriction_terms, :updated_by_id ],
      [ :trade_restrictions, :created_by_id ],
      [ :trade_restrictions, :end_notification_id ],
      [ :trade_restrictions, :geo_entity_id ],
      [ :trade_restrictions, :start_notification_id ],
      [ :trade_restrictions, :taxon_concept_id ],
      [ :trade_restrictions, :unit_id ],
      [ :trade_restrictions, :updated_by_id ],
      [ :trade_shipments, :created_by_id ],
      [ :trade_shipments, :trade_annual_report_upload_id ],
      [ :trade_shipments, :updated_by_id ]
    ]
  end
end
