SELECT DISTINCT id, year, appendix, taxon_concept_id,
       author_year,
       name_status,
       taxon_name,
       phylum_id,
       class_id,
       class_name,
       order_id,
       order_name,
       family_id,
       family_name,
       genus_id,
       genus_name,
       term_id,
       term,
       importer_reported_quantity,
       exporter_reported_quantity,
       unit_id,
       unit,
       exporter_id,
       exporter_iso,
       exporter,
       importer_id,
       importer_iso,
       importer,
       origin,
       purpose_id,
       purpose,
       source_id,
       source,
       import_permits,
       export_permits,
       origin_permits,
       import_permit,
       export_permit,
       origin_permit,
       rank_id,
       rank_name,
       issue_type::text
FROM trade_shipments_appendix_i_mview

UNION ALL

SELECT DISTINCT id, year, appendix, taxon_concept_id,
       author_year,
       name_status,
       taxon_name,
       phylum_id,
       class_id,
       class_name,
       order_id,
       order_name,
       family_id,
       family_name,
       genus_id,
       genus_name,
       term_id,
       term,
       importer_reported_quantity,
       exporter_reported_quantity,
       unit_id,
       unit,
       exporter_id,
       exporter_iso,
       exporter,
       importer_id,
       importer_iso,
       importer,
       origin,
       purpose_id,
       purpose,
       source_id,
       source,
       import_permits,
       export_permits,
       origin_permits,
       import_permit,
       export_permit,
       origin_permit,
       rank_id,
       rank_name,
       issue_type::text
FROM trade_shipments_mandatory_quotas_mview

UNION ALL

SELECT DISTINCT id, year, appendix, taxon_concept_id,
       author_year,
       name_status,
       taxon_name,
       phylum_id,
       class_id,
       class_name,
       order_id,
       order_name,
       family_id,
       family_name,
       genus_id,
       genus_name,
       term_id,
       term,
       importer_reported_quantity,
       exporter_reported_quantity,
       unit_id,
       unit,
       exporter_id,
       exporter_iso,
       exporter,
       importer_id,
       importer_iso,
       importer,
       origin,
       purpose_id,
       purpose,
       source_id,
       source,
       import_permits,
       export_permits,
       origin_permits,
       import_permit,
       export_permit,
       origin_permit,
       rank_id,
       rank_name,
       issue_type::text
FROM trade_shipments_cites_suspensions_mview
